[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor-example = "DzryzuZmt3y9qVsLzDMhZ6AHsarqhEDso5f34uCGvpaw"
anchor_bug_test = "8tn1PnNDZnvu6okWXmrci2VL8kStTEYoKzsy9vKCi7kf"
main-program = "9o9jDgtHAW2npTWDRGn5EFTpa6ALhivvjsx1Hj8JzxTH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/nvsriram/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
